### ISSUE TITLE
CDM-16 documentation: unclear description of shift and ls/ss instructions

### ISSUE THREAD

**Issue by dmitry-irtegov** [cdm-processors/cdm-devkit#24]
**Describe the bug**
Shift instructions are described as 
`CdM-16 has a barrel shifter that can performs shifts from 1 to 8 postitions, val determines distance of shift.`
It is unclear what is 'val': is it a register or immedate?
Am I correct that 'val' is imm3+1?  I.e. you cannot shift more than 8 bits in any direction?

ls/ss instructions are described as 
`Load word from stack. -...-`

fp/r7 register is primarily intended to be used as a frame pointer, so in many cases it really would point into the stack (but not to the stack top!).  But the programmer does not have to use it as a frame pointer.  For example, if the programmer wants to access several fields of a structure (and does not need frame accesses in between), he/she/it might point fp to the structure base and issue bunch of ls/ss commands.  As long as it follows the calling conventions (i.e. restores fp on return) it does nothing wrong.

Also, it is unclear, is fp + (imm6 * 2) formula true for word accesses or also to byte accesses.

**Comment by Intelix8996** [comment]
> Am I correct that 'val' is imm3+1? I.e. you cannot shift more than 8 bits in any direction?

In this case `val` is immediate number that can take values from 1 to 8. So, for example, `shl r0, r1, 2` corresponds to C-like `r1 = r0 << 2`, note that `val == 0` is not valid. Will add this to docs.

> Also, it is unclear, is fp + (imm6 * 2) formula true for word accesses or also to byte accesses.

Actually, that is a point to discuss. For now both byte and word variations count in words, that's why it is exactly `2` in the formula. But it seems like a good idea to make byte variation count in bytes. What would you suggest? Should we make byte versions count in bytes? 
And in this case, assembler should interpret this number as count of bytes, right? So for byte version it will pass this number as is, for word version it will divide it by 2 and check if it is odd?

**Comment by Intelix8996** [comment]
Came to these decisions:
+ Make `lsb`, `lssb`, `ssb` count offset in bytes rather then words 
+ Assembler should treat all offests as bytes

Will update documentation according to these changes.
